# Generated by Django 3.1.2 on 2020-12-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_ram', models.CharField(max_length=10, unique=True, verbose_name='RAM')),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_rom', models.CharField(max_length=10, unique=True, verbose_name='Bộ nhớ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
                ('price', models.FloatField(null=True, verbose_name='Giá')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='static/image', verbose_name='ảnh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Nhãn hiệu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ram', verbose_name='RAM')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rom', verbose_name='Bộ nhớ')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
    ]
