# Generated by Django 3.1.2 on 2020-12-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
